### ISSUE TITLE
sub-folders for modalities

### ISSUE THREAD

**Issue by choldgraf** [bids-standard/bids-examples#74] opened 2018-04-13 16:59 UTC
I think it'd be helpful if there were a way to distinguish examples for particular modalities. This could either be something like appending the modality name to each folder (e.g. `ieeg_ds100`), or we could put them in sub-folders (`BIDS-examples/meg/ds100` and `BIDS-examples/fmri/ds101`). There will be many datasets that have multiple modalities, but I think this would be useful to guide newcomers and make it easier for them to find the information they want.

**Comment by chrisfilo** [comment] 2018-04-13 17:10
This looks like a duplicate of https://github.com/INCF/BIDS-examples/issues/52...

**Comment by choldgraf** [comment] 2018-04-13 17:13
Ah sorry - I should have been clearer. Since I'm updating the validator right now I was suggesting this is something I could try implementing (changing the validator tests to reflect updated folder structure). If you think these two things should be done separately, then I can hold off.

**Comment by chrisfilo** [comment] 2018-04-17 22:07
The only concern I have is that most examples are multimodal so tags rather than folders would work better. But we cannot have tags. What about making the guide to examples more prominent by moving it from wiki to the README?

**Comment by robertoostenveld** [comment] 2018-04-18 11:45
agreed, I also consider the documentation in the wiki not obvious to find. We could also have a few README files, one for each logical grouping.

**Closed** 2019-05-08 07:41 UTC
Labels: maintenance
